version: '3.8'

services:

  # ── Postgres dev ─────────────────────────────────────
  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB:     ${POSTGRES_DB}
      POSTGRES_USER:   ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  # ── MinIO dev (S3‐compat) ─────────────────────────────W
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    env_file: .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - minio_data:/data


volumes:
  postgres_data:
  minio_data: