spring:
  application:
    name: mango-lab-backend
  profiles:
    active: ${PROFILE_ACTIVE:dev}

  # ── DATASOURCE ───────────────────────────────────────────────────
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # ── JPA ──────────────────────────────────────────────────────────
  jpa:
    hibernate:
      ddl-auto: ${HIBER_DDL_AUTO}      # Esempio: update in dev, validate in prod
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# ── FLYWAY (migrazioni automatiche) ───────────────────────────────
flyway:
  enabled: ${FLYWAY_ENABLED:true}
  locations: classpath:db/migration

# ── ACTUATOR ──────────────────────────────────────────────────────
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

# ── SERVER (porta, redirect http→https, ecc.) ────────────────────
server:
  port: ${SERVER_PORT:8080}