DATABASE_HOST: localhost
DATABASE_PORT: 5432
DATABASE_NAME: mango-lab-dev

HIBER_DDL_AUTO: create-drop
  
S3_ENDPOINT: http://localhost:9000
S3_REGION: us-east-1
S3_ACCESS_KEY: devkey
S3_SECRET_KEY: devsecret
S3_BUCKET_NAME: images

