spring:
  application:
    name: mango-lab-backend

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.${DATABASE_TYPE}Dialect
      ddl-auto: ${HIBER_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true

frontend:
  domain: ${FRONTEND_DOMAIN:http://localhost:4200}

management:
  endpoints:
    web:
      cors:
        allowed-origins: ${frontend.domain}
        allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

s3:
  endpoint: ${S3_ENDPOINT}
  region: ${S3_REGION}
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  bucket: ${S3_BUCKET_NAME}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO

application:
  log:
    path: ${LOG_PATH:./backend/logs}
    max-history: ${LOG_MAX_HISTORY:30}
    total-size-cap: ${LOG_TOTAL_SIZE_CAP:1GB}

server:
  port: ${SERVER_PORT:8080}