spring:
  application:
    name: mango-lab-backend
  profiles:
    active: ${PROFILE_ACTIVE:dev}

  # ── DATASOURCE ───────────────────────────────────────────────────
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # ── JPA ──────────────────────────────────────────────────────────
  jpa:
    hibernate:
      ddl-auto: ${HIBER_DDL_AUTO}      # Esempio: update in dev, validate in prod
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# ── FLYWAY (migrazioni automatiche) ───────────────────────────────
flyway:
  enabled: ${FLYWAY_ENABLED:true}
  locations: classpath:db/migration

# ── ACTUATOR ──────────────────────────────────────────────────────
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

# ── STORAGE ───────────────────────────────────────────────────────
s3:
  endpoint:    ${S3_ENDPOINT}
  region:      ${S3_REGION}
  access-key:  ${S3_ACCESS_KEY}
  secret-key:  ${S3_SECRET_KEY}
  bucket-name: ${S3_BUCKET_NAME}

# ── LOGGING ───────────────────────────────────────────────────────
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO

LOKI_ENDPOINT: ${LOKI_ENDPOINT:http://localhost:3100/loki/api/v1/push}
LOKI_API_KEY: ${LOKI_API_KEY:}

# ── SERVER (porta, redirect http→https, ecc.) ────────────────────
server:
  port: ${SERVER_PORT:8080}