name: CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Run backend tests
        run: |
          cd backend
          ./mvnw test

      - name: Build backend jar
        run: |
          cd backend
          ./mvnw package -DskipTests

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install & build
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Run frontend tests
        run: |
          cd frontend
          npm test
