# .github/workflows/pr-cleanup.yml
name: 🔥 Delete merged feature branches

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Delete feature branch
        uses: peter-evans/delete-branch@v5
        with:
          branch: ${{ github.event.pull_request.head.ref }}
